### ISSUE TITLE
Flat visualization

### ISSUE THREAD

**Issue by silexu** [siemensmacv/rubik-teacher#4]

**Comment by vladvrabie** [comment]
Input: un string de forma UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB
Output: reprezentarea in Qt de forma
 *                     |***************|
 *                     |*U1**U2**U3*|
 *                     |***************|
 *                     |*U4**U5**U6*|
 *                     |***************|
 *                     |*U7**U8**U9*|
 *                     |***************|
 * *************|***************|*************|**************|
 * *L1**L2**L3*|*F1**F2**F3*|*R1**R2**F3*|*B1**B2**B3*|
 * *************|**************|**************|**************|
 * *L4**L5**L6*|*F4**F5**F6*|*R4**R5**R6*|*B4**B5**B6*|
 * *************|**************|**************|**************|
 * *L7**L8**L9*|*F7**F8**F9*|*R7**R8**R9*|*B7**B8**B9*|
 * *************|***************|**************|**************|
 *                     |***************|
 *                     |*D1**D2**D3*|
 *                     |***************|
 *                     |*D4**D5**D6*|
 *                     |***************|
 *                     |*D7**D8**D9*|
 *                     |***************|

**Comment by cosminpolifronie** [comment]
Done.
